### ISSUE TITLE
为什么你的仓库名能以自己的域名命名？

### ISSUE THREAD

**Issue by zhuziyi1989** [pinggod/pinggod.com#1]
为什么你的仓库名能以自己的域名命名？

而我只能用  username.github.io命名才可以。

**Comment by pinggod** [comment]
在仓库的根目录下创建 `CNAME` 文件，文件内容为域名地址，比如我的 CNAME 文件内容为：

```plain
pinggod.com
```

**Comment by zhuziyi1989** [comment]
我也是这么设置的，我再试试。
