### ISSUE TITLE
能给apollo主题加上分类和标签的功能吗

### ISSUE THREAD

**Issue by twimb** [pinggod/pinggod.com#2]
apollo 项目中不能 issues ，所以就写在这里了，感谢开源了你的主题，希望能加上分类和标签的功能，原谅我不了解前端的知识。

**Comment by pinggod** [comment]
@twimb 

感谢你的建议，但是鉴于目前我的时间安排，只会对该主题存在的问题进行修复，不会再新增新的功能，只能说声抱歉了。

**Comment by twimb** [comment]
那我自己研究研究吧，最后还是得谢谢你做了这么漂亮和我心意的hexo-theme
