### ISSUE TITLE
请问怎么使用自己的多说？

### ISSUE THREAD

**Issue by BangKk** [pinggod/pinggod.com#3]
您好，我用了你的hexo-theme-apollo这个主题，但是我增加的评论功能中都显示的是你的多说，请问这个怎么解决？
![image](https://cloud.githubusercontent.com/assets/13979818/20060141/a4f6043a-a534-11e6-83f4-eeeb66dea7d0.png)

**Comment by pinggod** [comment]
https://github.com/pinggod/hexo-theme-apollo/blob/master/_config.yml#L14 在这里填写你的多说帐号

**Comment by BangKk** [comment]
谢谢！
